// Provenance : ISO 3166-1 alpha-2 (https://www.iso.org/iso-3166-country-codes.html).
// Noms affichés en français. Liste maintenable : ajouter/retirer une entrée ici
// suffit à étendre la validation Zod et le sélecteur pays côté client.
// Aucune dépendance externe n'est nécessaire pour cette liste statique.
export const COUNTRIES = [
  { code: "AF", nameFr: "Afghanistan" },
  { code: "ZA", nameFr: "Afrique du Sud" },
  { code: "AX", nameFr: "Îles Åland" },
  { code: "AL", nameFr: "Albanie" },
  { code: "DZ", nameFr: "Algérie" },
  { code: "DE", nameFr: "Allemagne" },
  { code: "AD", nameFr: "Andorre" },
  { code: "AO", nameFr: "Angola" },
  { code: "AI", nameFr: "Anguilla" },
  { code: "AQ", nameFr: "Antarctique" },
  { code: "AG", nameFr: "Antigua-et-Barbuda" },
  { code: "SA", nameFr: "Arabie saoudite" },
  { code: "AR", nameFr: "Argentine" },
  { code: "AM", nameFr: "Arménie" },
  { code: "AW", nameFr: "Aruba" },
  { code: "AU", nameFr: "Australie" },
  { code: "AT", nameFr: "Autriche" },
  { code: "AZ", nameFr: "Azerbaïdjan" },
  { code: "BS", nameFr: "Bahamas" },
  { code: "BH", nameFr: "Bahreïn" },
  { code: "BD", nameFr: "Bangladesh" },
  { code: "BB", nameFr: "Barbade" },
  { code: "BY", nameFr: "Biélorussie" },
  { code: "BE", nameFr: "Belgique" },
  { code: "BZ", nameFr: "Belize" },
  { code: "BJ", nameFr: "Bénin" },
  { code: "BM", nameFr: "Bermudes" },
  { code: "BT", nameFr: "Bhoutan" },
  { code: "BO", nameFr: "Bolivie" },
  { code: "BQ", nameFr: "Bonaire, Saint-Eustache et Saba" },
  { code: "BA", nameFr: "Bosnie-Herzégovine" },
  { code: "BW", nameFr: "Botswana" },
  { code: "BV", nameFr: "Île Bouvet" },
  { code: "BR", nameFr: "Brésil" },
  { code: "BN", nameFr: "Brunei" },
  { code: "BG", nameFr: "Bulgarie" },
  { code: "BF", nameFr: "Burkina Faso" },
  { code: "BI", nameFr: "Burundi" },
  { code: "KY", nameFr: "Îles Caïmans" },
  { code: "KH", nameFr: "Cambodge" },
  { code: "CM", nameFr: "Cameroun" },
  { code: "CA", nameFr: "Canada" },
  { code: "CV", nameFr: "Cap-Vert" },
  { code: "CF", nameFr: "République centrafricaine" },
  { code: "CL", nameFr: "Chili" },
  { code: "CN", nameFr: "Chine" },
  { code: "CX", nameFr: "Île Christmas" },
  { code: "CY", nameFr: "Chypre" },
  { code: "CC", nameFr: "Îles Cocos" },
  { code: "CO", nameFr: "Colombie" },
  { code: "KM", nameFr: "Comores" },
  { code: "CG", nameFr: "République du Congo" },
  { code: "CD", nameFr: "République démocratique du Congo" },
  { code: "CK", nameFr: "Îles Cook" },
  { code: "KR", nameFr: "Corée du Sud" },
  { code: "KP", nameFr: "Corée du Nord" },
  { code: "CR", nameFr: "Costa Rica" },
  { code: "CI", nameFr: "Côte d'Ivoire" },
  { code: "HR", nameFr: "Croatie" },
  { code: "CU", nameFr: "Cuba" },
  { code: "CW", nameFr: "Curaçao" },
  { code: "DK", nameFr: "Danemark" },
  { code: "DJ", nameFr: "Djibouti" },
  { code: "DO", nameFr: "République dominicaine" },
  { code: "DM", nameFr: "Dominique" },
  { code: "EG", nameFr: "Égypte" },
  { code: "AE", nameFr: "Émirats arabes unis" },
  { code: "EC", nameFr: "Équateur" },
  { code: "ER", nameFr: "Érythrée" },
  { code: "ES", nameFr: "Espagne" },
  { code: "EE", nameFr: "Estonie" },
  { code: "SZ", nameFr: "Eswatini" },
  { code: "US", nameFr: "États-Unis" },
  { code: "ET", nameFr: "Éthiopie" },
  { code: "FK", nameFr: "Îles Falkland (Malouines)" },
  { code: "FO", nameFr: "Îles Féroé" },
  { code: "FJ", nameFr: "Fidji" },
  { code: "FI", nameFr: "Finlande" },
  { code: "FR", nameFr: "France" },
  { code: "GA", nameFr: "Gabon" },
  { code: "GM", nameFr: "Gambie" },
  { code: "GE", nameFr: "Géorgie" },
  { code: "GS", nameFr: "Géorgie du Sud-et-les Îles Sandwich du Sud" },
  { code: "GH", nameFr: "Ghana" },
  { code: "GI", nameFr: "Gibraltar" },
  { code: "GR", nameFr: "Grèce" },
  { code: "GD", nameFr: "Grenade" },
  { code: "GL", nameFr: "Groenland" },
  { code: "GP", nameFr: "Guadeloupe" },
  { code: "GU", nameFr: "Guam" },
  { code: "GT", nameFr: "Guatemala" },
  { code: "GG", nameFr: "Guernesey" },
  { code: "GN", nameFr: "Guinée" },
  { code: "GW", nameFr: "Guinée-Bissau" },
  { code: "GQ", nameFr: "Guinée équatoriale" },
  { code: "GY", nameFr: "Guyana" },
  { code: "GF", nameFr: "Guyane française" },
  { code: "HT", nameFr: "Haïti" },
  { code: "HM", nameFr: "Îles Heard-et-MacDonald" },
  { code: "HN", nameFr: "Honduras" },
  { code: "HK", nameFr: "Hong Kong" },
  { code: "HU", nameFr: "Hongrie" },
  { code: "IM", nameFr: "Île de Man" },
  { code: "UM", nameFr: "Îles mineures éloignées des États-Unis" },
  { code: "VG", nameFr: "Îles Vierges britanniques" },
  { code: "VI", nameFr: "Îles Vierges des États-Unis" },
  { code: "IN", nameFr: "Inde" },
  { code: "ID", nameFr: "Indonésie" },
  { code: "IR", nameFr: "Iran" },
  { code: "IQ", nameFr: "Irak" },
  { code: "IE", nameFr: "Irlande" },
  { code: "IS", nameFr: "Islande" },
  { code: "IL", nameFr: "Israël" },
  { code: "IT", nameFr: "Italie" },
  { code: "JM", nameFr: "Jamaïque" },
  { code: "JP", nameFr: "Japon" },
  { code: "JE", nameFr: "Jersey" },
  { code: "JO", nameFr: "Jordanie" },
  { code: "KZ", nameFr: "Kazakhstan" },
  { code: "KE", nameFr: "Kenya" },
  { code: "KG", nameFr: "Kirghizistan" },
  { code: "KI", nameFr: "Kiribati" },
  { code: "KW", nameFr: "Koweït" },
  { code: "LA", nameFr: "Laos" },
  { code: "LS", nameFr: "Lesotho" },
  { code: "LV", nameFr: "Lettonie" },
  { code: "LB", nameFr: "Liban" },
  { code: "LR", nameFr: "Liberia" },
  { code: "LY", nameFr: "Libye" },
  { code: "LI", nameFr: "Liechtenstein" },
  { code: "LT", nameFr: "Lituanie" },
  { code: "LU", nameFr: "Luxembourg" },
  { code: "MO", nameFr: "Macao" },
  { code: "MK", nameFr: "Macédoine du Nord" },
  { code: "MG", nameFr: "Madagascar" },
  { code: "MY", nameFr: "Malaisie" },
  { code: "MW", nameFr: "Malawi" },
  { code: "MV", nameFr: "Maldives" },
  { code: "ML", nameFr: "Mali" },
  { code: "MT", nameFr: "Malte" },
  { code: "MP", nameFr: "Îles Mariannes du Nord" },
  { code: "MA", nameFr: "Maroc" },
  { code: "MH", nameFr: "Îles Marshall" },
  { code: "MQ", nameFr: "Martinique" },
  { code: "MU", nameFr: "Maurice" },
  { code: "MR", nameFr: "Mauritanie" },
  { code: "YT", nameFr: "Mayotte" },
  { code: "MX", nameFr: "Mexique" },
  { code: "FM", nameFr: "Micronésie" },
  { code: "MD", nameFr: "Moldavie" },
  { code: "MC", nameFr: "Monaco" },
  { code: "MN", nameFr: "Mongolie" },
  { code: "ME", nameFr: "Monténégro" },
  { code: "MS", nameFr: "Montserrat" },
  { code: "MZ", nameFr: "Mozambique" },
  { code: "MM", nameFr: "Myanmar (Birmanie)" },
  { code: "NA", nameFr: "Namibie" },
  { code: "NR", nameFr: "Nauru" },
  { code: "NP", nameFr: "Népal" },
  { code: "NI", nameFr: "Nicaragua" },
  { code: "NE", nameFr: "Niger" },
  { code: "NG", nameFr: "Nigeria" },
  { code: "NU", nameFr: "Niue" },
  { code: "NF", nameFr: "Île Norfolk" },
  { code: "NO", nameFr: "Norvège" },
  { code: "NC", nameFr: "Nouvelle-Calédonie" },
  { code: "NZ", nameFr: "Nouvelle-Zélande" },
  { code: "OM", nameFr: "Oman" },
  { code: "UG", nameFr: "Ouganda" },
  { code: "UZ", nameFr: "Ouzbékistan" },
  { code: "PK", nameFr: "Pakistan" },
  { code: "PW", nameFr: "Palaos" },
  { code: "PS", nameFr: "Palestine" },
  { code: "PA", nameFr: "Panama" },
  { code: "PG", nameFr: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", nameFr: "Paraguay" },
  { code: "NL", nameFr: "Pays-Bas" },
  { code: "PE", nameFr: "Pérou" },
  { code: "PH", nameFr: "Philippines" },
  { code: "PN", nameFr: "Îles Pitcairn" },
  { code: "PL", nameFr: "Pologne" },
  { code: "PF", nameFr: "Polynésie française" },
  { code: "PR", nameFr: "Porto Rico" },
  { code: "PT", nameFr: "Portugal" },
  { code: "QA", nameFr: "Qatar" },
  { code: "RE", nameFr: "La Réunion" },
  { code: "RO", nameFr: "Roumanie" },
  { code: "GB", nameFr: "Royaume-Uni" },
  { code: "RU", nameFr: "Russie" },
  { code: "RW", nameFr: "Rwanda" },
  { code: "EH", nameFr: "Sahara occidental" },
  { code: "BL", nameFr: "Saint-Barthélemy" },
  { code: "SH", nameFr: "Sainte-Hélène" },
  { code: "LC", nameFr: "Sainte-Lucie" },
  { code: "KN", nameFr: "Saint-Christophe-et-Niévès" },
  { code: "SM", nameFr: "Saint-Marin" },
  { code: "MF", nameFr: "Saint-Martin" },
  { code: "SX", nameFr: "Saint-Martin (partie néerlandaise)" },
  { code: "PM", nameFr: "Saint-Pierre-et-Miquelon" },
  { code: "VA", nameFr: "Saint-Siège (Vatican)" },
  { code: "VC", nameFr: "Saint-Vincent-et-les-Grenadines" },
  { code: "SB", nameFr: "Îles Salomon" },
  { code: "SV", nameFr: "Salvador" },
  { code: "WS", nameFr: "Samoa" },
  { code: "AS", nameFr: "Samoa américaines" },
  { code: "ST", nameFr: "Sao Tomé-et-Principe" },
  { code: "SN", nameFr: "Sénégal" },
  { code: "RS", nameFr: "Serbie" },
  { code: "SC", nameFr: "Seychelles" },
  { code: "SL", nameFr: "Sierra Leone" },
  { code: "SG", nameFr: "Singapour" },
  { code: "SK", nameFr: "Slovaquie" },
  { code: "SI", nameFr: "Slovénie" },
  { code: "SO", nameFr: "Somalie" },
  { code: "SD", nameFr: "Soudan" },
  { code: "SS", nameFr: "Soudan du Sud" },
  { code: "LK", nameFr: "Sri Lanka" },
  { code: "SE", nameFr: "Suède" },
  { code: "CH", nameFr: "Suisse" },
  { code: "SR", nameFr: "Suriname" },
  { code: "SJ", nameFr: "Svalbard et Jan Mayen" },
  { code: "TJ", nameFr: "Tadjikistan" },
  { code: "TW", nameFr: "Taïwan" },
  { code: "TZ", nameFr: "Tanzanie" },
  { code: "TD", nameFr: "Tchad" },
  { code: "CZ", nameFr: "Tchéquie" },
  { code: "TF", nameFr: "Terres australes françaises" },
  { code: "IO", nameFr: "Territoire britannique de l'océan Indien" },
  { code: "TH", nameFr: "Thaïlande" },
  { code: "TL", nameFr: "Timor oriental" },
  { code: "TG", nameFr: "Togo" },
  { code: "TK", nameFr: "Tokelau" },
  { code: "TO", nameFr: "Tonga" },
  { code: "TT", nameFr: "Trinité-et-Tobago" },
  { code: "TN", nameFr: "Tunisie" },
  { code: "TM", nameFr: "Turkménistan" },
  { code: "TC", nameFr: "Îles Turques-et-Caïques" },
  { code: "TR", nameFr: "Turquie" },
  { code: "TV", nameFr: "Tuvalu" },
  { code: "UA", nameFr: "Ukraine" },
  { code: "UY", nameFr: "Uruguay" },
  { code: "VU", nameFr: "Vanuatu" },
  { code: "VE", nameFr: "Venezuela" },
  { code: "VN", nameFr: "Viêt Nam" },
  { code: "WF", nameFr: "Wallis-et-Futuna" },
  { code: "YE", nameFr: "Yémen" },
  { code: "ZM", nameFr: "Zambie" },
  { code: "ZW", nameFr: "Zimbabwe" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["code"];

export const COUNTRY_NAME_BY_CODE: Record<CountryCode, string> = Object.fromEntries(
  COUNTRIES.map((country) => [country.code, country.nameFr]),
) as Record<CountryCode, string>;

export function isCountryCode(value: string): value is CountryCode {
  return Object.prototype.hasOwnProperty.call(COUNTRY_NAME_BY_CODE, value);
}
